CREATE TABLE liwc_features_covid_include_title_custom_tokenize (
    reddit_id bigint NOT NULL,
    comment boolean NOT NULL,
    achiev smallint NOT NULL,
    adj smallint NOT NULL,
    adverb smallint NOT NULL,
    affect smallint NOT NULL,
    affiliation smallint NOT NULL,
    anger smallint NOT NULL,
    anx smallint NOT NULL,
    article smallint NOT NULL,
    assent smallint NOT NULL,
    auxverb smallint NOT NULL,
    bio smallint NOT NULL,
    body smallint NOT NULL,
    cause smallint NOT NULL,
    certain smallint NOT NULL,
    cogproc smallint NOT NULL,
    compare smallint NOT NULL,
    conj smallint NOT NULL,
    death smallint NOT NULL,
    differ smallint NOT NULL,
    discrep smallint NOT NULL,
    drives smallint NOT NULL,
    family smallint NOT NULL,
    feel smallint NOT NULL,
    female smallint NOT NULL,
    filler smallint NOT NULL,
    focusfuture smallint NOT NULL,
    focuspast smallint NOT NULL,
    focuspresent smallint NOT NULL,
    friend smallint NOT NULL,
    function smallint NOT NULL,
    health smallint NOT NULL,
    hear smallint NOT NULL,
    home smallint NOT NULL,
    i smallint NOT NULL,
    informal smallint NOT NULL,
    ingest smallint NOT NULL,
    insight smallint NOT NULL,
    interrog smallint NOT NULL,
    ipron smallint NOT NULL,
    leisure smallint NOT NULL,
    male smallint NOT NULL,
    money smallint NOT NULL,
    motion smallint NOT NULL,
    negate smallint NOT NULL,
    negemo smallint NOT NULL,
    netspeak smallint NOT NULL,
    nonflu smallint NOT NULL,
    number smallint NOT NULL,
    percept smallint NOT NULL,
    posemo smallint NOT NULL,
    power smallint NOT NULL,
    ppron smallint NOT NULL,
    prep smallint NOT NULL,
    pronoun smallint NOT NULL,
    quant smallint NOT NULL,
    relativ smallint NOT NULL,
    relig smallint NOT NULL,
    reward smallint NOT NULL,
    risk smallint NOT NULL,
    sad smallint NOT NULL,
    see smallint NOT NULL,
    sexual smallint NOT NULL,
    shehe smallint NOT NULL,
    social smallint NOT NULL,
    space smallint NOT NULL,
    swear smallint NOT NULL,
    tentat smallint NOT NULL,
    they smallint NOT NULL,
    "time" smallint NOT NULL,
    verb smallint NOT NULL,
    we smallint NOT NULL,
    work smallint NOT NULL,
    you smallint NOT NULL,
    word_count smallint NOT NULL,
);


ALTER TABLE ONLY liwc_features_covid_include_title_custom_tokenize
    ADD CONSTRAINT liwc_features_covid_include_title_custom_tokenize_pkey PRIMARY KEY (reddit_id, comment);

CREATE TABLE covid_term_count (
    reddit_id bigint NOT NULL,
    comment boolean NOT NULL,
    subreddit character varying(50) NOT NULL,
    author character varying(50) NOT NULL,
    date timestamp without time zone NOT NULL,
    count_2019_ncov smallint NOT NULL,
    count_2019ncov smallint NOT NULL,
    count_corona smallint NOT NULL,
    count_coronavirus smallint NOT NULL,
    count_covid smallint NOT NULL,
    count_covid_19 smallint NOT NULL,
    count_covid19 smallint NOT NULL,
    count_mers smallint NOT NULL,
    count_outbreak smallint NOT NULL,
    count_pandemic smallint NOT NULL,
    count_rona smallint NOT NULL,
    count_sars smallint NOT NULL,
    count_sars_cov_2 smallint NOT NULL,
    count_sars2 smallint NOT NULL,
    count_sarscov19 smallint NOT NULL,
    count_virus smallint NOT NULL,
    count_wuflu smallint NOT NULL,
    count_wuhan smallint NOT NULL,
    word_count smallint NOT NULL
);

ALTER TABLE ONLY covid_term_count
    ADD CONSTRAINT covid_term_count_pkey PRIMARY KEY (reddit_id, comment);